# Generated by Django 4.1.7 on 2023-03-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('عنوان', models.CharField(max_length=200)),
                ('نویسنده', models.CharField(max_length=200)),
                ('توضیحات', models.TextField()),
                ('مترجم', models.CharField(max_length=150)),
                ('ناشر', models.CharField(max_length=150)),
                ('تعداد_صفحات', models.PositiveIntegerField()),
                ('قیمت', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
