# Generated by Django 4.1.7 on 2023-03-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='عکس_کتاب',
            field=models.ImageField(blank=True, upload_to='book_cover'),
        ),
    ]
