# Generated by Django 4.1.7 on 2023-03-27 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_alter_book_عکس_کتاب'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='عکس_کتاب',
            new_name='cover',
        ),
    ]
